name: todo
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9
  gap: ^3.0.1
  icofont_flutter: ^1.4.0
  change_app_package_name: ^1.1.0
  equatable: ^2.0.5
  logger: ^2.0.2+1
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  mask_text_input_formatter: ^2.7.0
  uuid: ^4.2.1
  zoom_tap_animation: ^1.1.0
  sqflite: ^2.3.0
  url_launcher: ^6.2.1
  fluttertoast: ^8.2.4
  stream_transform: ^2.1.0
  bloc_concurrency: ^0.2.2
  cached_network_image: ^3.3.0
  build_runner: ^2.4.7
  awesome_dialog: ^3.1.0
  awesome_extensions: ^2.0.10
  path: ^1.8.3
  cupertino_icons: ^1.0.6
  flutter_rating_bar: ^4.0.1
  loading_animation_widget: ^1.2.0+4
  quickalert: ^1.0.2
  flutter_share: ^2.0.0
  flutter_screenutil: ^5.9.0
  carousel_slider: ^4.2.1
  lottie: ^2.7.0
  easy_localization: ^3.0.3
  dio: ^5.4.0
  http: ^1.1.2
  syncfusion_flutter_calendar: ^23.2.6
  babstrap_settings_screen: ^0.1.6



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1




flutter:
  uses-material-design: true


  assets:
    - assets/images/
    - assets/svg/
  #    - assets/translations/


#  fonts:
#    - family: Sora
#      fonts:
#        - asset: assets/fonts/Sora-Regular.ttf
#        - asset: assets/fonts/Sora-Light.ttf
#        - asset: assets/fonts/Sora-Medium.ttf
#        - asset: assets/fonts/Sora-SemiBold.ttf
#        - asset: assets/fonts/Sora-Bold.ttf
#        - asset: assets/fonts/Sora-ExtraBold.ttf
#          style: italic
